export const DEVANAGARI_ONLY = 'DEVANAGARI_ONLY'
export const DEVANAGARI_WITH_IAST = 'DEVANAGARI_WITH_IAST'
export const IAST_ONLY = 'IAST_ONLY'
export const IAST_WITH_DEVANAGARI = 'IAST_WITH_DEVANAGARI'
